### ISSUE TITLE
Hello, I would like to know the final outcome of this article. Sorry, I haven't learned how to find this information yet. >_<

### ISSUE THREAD

**Issue by qcjySONG** [LancelotXWX/MAG-SQL#2]
thanks

**Comment by Lancelot-Xie** [comment]
Sure, do you want to know the results on the BIRD dataset?

**Comment by qcjySONG** [comment]
Sorry for the ambiguity in my expression. Actually, I wanted to know which journal or conference this paper was published in.

**Comment by Lancelot-Xie** [comment]
Oh, sorry for my misunderstanding. Due to some reasons, this paper was not submitted to any conference.
